require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'



target 'FoodDeliveryAppTemplate' do
  
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'FoodDeliveryAppTemplateTests' do
    inherit! :complete
    # Pods for testing
  end

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({'Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1'})
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'FoodDeliveryAppTemplate-tvOS' do
  # Pods for FoodDeliveryAppTemplate-tvOS

  target 'FoodDeliveryAppTemplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
